OPTIM:
  METHOD: "Adam"
  STEPS: 1
  BETA: 0.9
  LR: 0.001
  WD: 0.
  MOMENTUM: 0.9

ADAPTER:
  NAME: TEA
  TEA:
    UNCOND: uncond
    STEPS: 20
    SGLD_LR: 0.1
    SGLD_STD: 0.01
    BUFFER_SIZE: 10000
    REINIT_FREQ: 0.05
    IMG_SIZE: 224
    NUM_CHANNEL: 3